### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by SunshineSpring666** [fkozaslan/MAUI-Accordion-View#1]
Hi Kubra,
    The accordion control is awesome. Could you please release a NuGet package so that MAUI app developers can easily use it in projects?
    Thanks a lot.
    Regards

**Comment by kbrkiras** [comment]
Hi, of course i can post it on nuget as soon as possible. I will write comment on this issue when publish

**Comment by kbrkiras** [comment]
** Package published
https://www.nuget.org/packages/KbrKiras.MAUIAccordionComponent/

**Comment by SunshineSpring666** [comment]
Thanks, Kubra ; )
